spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aqt?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: LeBronJames123450
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8081
